// FIFA World Cup 2026 matches database (104 matches)
const matches = [
  {
    "id": 1,
    "stage": "Group Stage",
    "group": "Group A",
    "team1": "Mexico",
    "team2": "South Africa",
    "team1_code": "mx",
    "team2_code": "za",
    "utc_time": "2026-06-11T21:30:00Z",
    "venue": "Mexico City Stadium, Mexico City",
    "score1": 2,
    "score2": 0,
    "status": "Completed",
    "featured": true
  },
  {
    "id": 2,
    "stage": "Group Stage",
    "group": "Group A",
    "team1": "Korea Republic",
    "team2": "Czechia",
    "team1_code": "kr",
    "team2_code": "cz",
    "utc_time": "2026-06-12T01:00:00Z",
    "venue": "Guadalajara Stadium, Guadalajara",
    "score1": 2,
    "score2": 1,
    "status": "Completed",
    "featured": false
  },
  {
    "id": 3,
    "stage": "Group Stage",
    "group": "Group B",
    "team1": "Canada",
    "team2": "Bosnia and Herzegovina",
    "team1_code": "ca",
    "team2_code": "ba",
    "utc_time": "2026-06-12T23:00:00Z",
    "venue": "Toronto Stadium, Toronto",
    "score1": 1,
    "score2": 1,
    "status": "Completed",
    "featured": false
  },
  {
    "id": 4,
    "stage": "Group Stage",
    "group": "Group D",
    "team1": "USA",
    "team2": "Paraguay",
    "team1_code": "us",
    "team2_code": "py",
    "utc_time": "2026-06-13T02:00:00Z",
    "venue": "Los Angeles Stadium, Los Angeles",
    "score1": 4,
    "score2": 1,
    "status": "Completed",
    "featured": false
  },
  {
    "id": 5,
    "stage": "Group Stage",
    "group": "Group B",
    "team1": "Qatar",
    "team2": "Switzerland",
    "team1_code": "qa",
    "team2_code": "ch",
    "utc_time": "2026-06-13T17:00:00Z",
    "venue": "San Francisco Bay Area Stadium, Santa Clara",
    "score1": 1,
    "score2": 1,
    "status": "Completed",
    "featured": false
  },
  {
    "id": 6,
    "stage": "Group Stage",
    "group": "Group C",
    "team1": "Brazil",
    "team2": "Morocco",
    "team1_code": "br",
    "team2_code": "ma",
    "utc_time": "2026-06-13T23:00:00Z",
    "venue": "New York/New Jersey Stadium, East Rutherford",
    "score1": 1,
    "score2": 1,
    "status": "Completed",
    "featured": false
  },
  {
    "id": 7,
    "stage": "Group Stage",
    "group": "Group C",
    "team1": "Haiti",
    "team2": "Scotland",
    "team1_code": "ht",
    "team2_code": "gb-sct",
    "utc_time": "2026-06-14T02:00:00Z",
    "venue": "Boston Stadium, Boston",
    "score1": 0,
    "score2": 1,
    "status": "Completed",
    "featured": false
  },
  {
    "id": 8,
    "stage": "Group Stage",
    "group": "Group E",
    "team1": "Germany",
    "team2": "Curaçao",
    "team1_code": "de",
    "team2_code": "cw",
    "utc_time": "2026-06-14T17:00:00Z",
    "venue": "Houston Stadium, Houston",
    "score1": 7,
    "score2": 1,
    "status": "Completed",
    "featured": false
  },
  {
    "id": 9,
    "stage": "Group Stage",
    "group": "Group D",
    "team1": "Australia",
    "team2": "Türkiye",
    "team1_code": "au",
    "team2_code": "tr",
    "utc_time": "2026-06-14T20:00:00Z",
    "venue": "BC Place Vancouver, Vancouver",
    "score1": 2,
    "score2": 0,
    "status": "Completed",
    "featured": false
  },
  {
    "id": 10,
    "stage": "Group Stage",
    "group": "Group E",
    "team1": "Côte d'Ivoire",
    "team2": "Ecuador",
    "team1_code": "ci",
    "team2_code": "ec",
    "utc_time": "2026-06-14T20:00:00Z",
    "venue": "Philadelphia Stadium, Philadelphia",
    "score1": 1,
    "score2": 0,
    "status": "Completed",
    "featured": false
  },
  {
    "id": 11,
    "stage": "Group Stage",
    "group": "Group F",
    "team1": "Netherlands",
    "team2": "Japan",
    "team1_code": "nl",
    "team2_code": "jp",
    "utc_time": "2026-06-14T23:00:00Z",
    "venue": "Dallas Stadium, Arlington",
    "score1": 2,
    "score2": 2,
    "status": "Completed",
    "featured": false
  },
  {
    "id": 12,
    "stage": "Group Stage",
    "group": "Group F",
    "team1": "Sweden",
    "team2": "Tunisia",
    "team1_code": "se",
    "team2_code": "tn",
    "utc_time": "2026-06-15T02:00:00Z",
    "venue": "Monterrey Stadium, Monterrey",
    "score1": 5,
    "score2": 1,
    "status": "Completed",
    "featured": false
  },
  {
    "id": 13,
    "stage": "Group Stage",
    "group": "Group G",
    "team1": "Belgium",
    "team2": "Egypt",
    "team1_code": "be",
    "team2_code": "eg",
    "utc_time": "2026-06-15T17:00:00Z",
    "venue": "Seattle Stadium, Seattle",
    "score1": 1,
    "score2": 1,
    "status": "Completed",
    "featured": false
  },
  {
    "id": 14,
    "stage": "Group Stage",
    "group": "Group H",
    "team1": "Spain",
    "team2": "Cabo Verde",
    "team1_code": "es",
    "team2_code": "cv",
    "utc_time": "2026-06-15T23:00:00Z",
    "venue": "Atlanta Stadium, Atlanta",
    "score1": 0,
    "score2": 0,
    "status": "Completed",
    "featured": false
  },
  {
    "id": 15,
    "stage": "Group Stage",
    "group": "Group G",
    "team1": "IR Iran",
    "team2": "New Zealand",
    "team1_code": "ir",
    "team2_code": "nz",
    "utc_time": "2026-06-16T02:00:00Z",
    "venue": "Los Angeles Stadium, Los Angeles",
    "score1": 2,
    "score2": 2,
    "status": "Completed",
    "featured": false
  },
  {
    "id": 16,
    "stage": "Group Stage",
    "group": "Group H",
    "team1": "Saudi Arabia",
    "team2": "Uruguay",
    "team1_code": "sa",
    "team2_code": "uy",
    "utc_time": "2026-06-16T02:00:00Z",
    "venue": "Miami Stadium, Miami",
    "score1": 1,
    "score2": 1,
    "status": "Completed",
    "featured": false
  },
  {
    "id": 17,
    "stage": "Group Stage",
    "group": "Group I",
    "team1": "France",
    "team2": "Senegal",
    "team1_code": "fr",
    "team2_code": "sn",
    "utc_time": "2026-06-16T19:00:00Z",
    "venue": "New York/New Jersey Stadium, East Rutherford",
    "score1": 3,
    "score2": 1,
    "status": "Completed",
    "featured": false
  },
  {
    "id": 18,
    "stage": "Group Stage",
    "group": "Group I",
    "team1": "Iraq",
    "team2": "Norway",
    "team1_code": "iq",
    "team2_code": "no",
    "utc_time": "2026-06-16T22:00:00Z",
    "venue": "Boston Stadium, Boston",
    "score1": 1,
    "score2": 4,
    "status": "Completed",
    "featured": false
  },
  {
    "id": 19,
    "stage": "Group Stage",
    "group": "Group J",
    "team1": "Argentina",
    "team2": "Algeria",
    "team1_code": "ar",
    "team2_code": "dz",
    "utc_time": "2026-06-17T01:00:00Z",
    "venue": "Kansas City Stadium, Kansas City",
    "score1": 3,
    "score2": 0,
    "status": "Completed",
    "featured": false
  },
  {
    "id": 20,
    "stage": "Group Stage",
    "group": "Group J",
    "team1": "Austria",
    "team2": "Jordan",
    "team1_code": "at",
    "team2_code": "jo",
    "utc_time": "2026-06-17T04:00:00Z",
    "venue": "San Francisco Bay Area Stadium, Santa Clara",
    "score1": 3,
    "score2": 1,
    "status": "Completed",
    "featured": false
  },
  {
    "id": 21,
    "stage": "Group Stage",
    "group": "Group K",
    "team1": "Portugal",
    "team2": "Congo DR",
    "team1_code": "pt",
    "team2_code": "cd",
    "utc_time": "2026-06-17T17:00:00Z",
    "venue": "Houston Stadium, Houston",
    "score1": 1,
    "score2": 1,
    "status": "Completed",
    "featured": false
  },
  {
    "id": 22,
    "stage": "Group Stage",
    "group": "Group L",
    "team1": "England",
    "team2": "Croatia",
    "team1_code": "gb-eng",
    "team2_code": "hr",
    "utc_time": "2026-06-17T20:00:00Z",
    "venue": "Dallas Stadium, Arlington",
    "score1": 4,
    "score2": 2,
    "status": "Completed",
    "featured": false
  },
  {
    "id": 23,
    "stage": "Group Stage",
    "group": "Group L",
    "team1": "Ghana",
    "team2": "Panama",
    "team1_code": "gh",
    "team2_code": "pa",
    "utc_time": "2026-06-17T23:00:00Z",
    "venue": "Toronto Stadium, Toronto",
    "score1": 1,
    "score2": 0,
    "status": "Completed",
    "featured": false
  },
  {
    "id": 24,
    "stage": "Group Stage",
    "group": "Group K",
    "team1": "Uzbekistan",
    "team2": "Colombia",
    "team1_code": "uz",
    "team2_code": "co",
    "utc_time": "2026-06-18T02:00:00Z",
    "venue": "Mexico City Stadium, Mexico City",
    "score1": 1,
    "score2": 3,
    "status": "Completed",
    "featured": false
  },
  {
    "id": 25,
    "stage": "Group Stage",
    "group": "Group A",
    "team1": "Czechia",
    "team2": "South Africa",
    "team1_code": "cz",
    "team2_code": "za",
    "utc_time": "2026-06-18T16:00:00Z",
    "venue": "Atlanta Stadium, Atlanta",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 26,
    "stage": "Group Stage",
    "group": "Group B",
    "team1": "Switzerland",
    "team2": "Bosnia and Herzegovina",
    "team1_code": "ch",
    "team2_code": "ba",
    "utc_time": "2026-06-18T19:00:00Z",
    "venue": "Los Angeles Stadium, Los Angeles",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 27,
    "stage": "Group Stage",
    "group": "Group B",
    "team1": "Canada",
    "team2": "Qatar",
    "team1_code": "ca",
    "team2_code": "qa",
    "utc_time": "2026-06-18T22:00:00Z",
    "venue": "BC Place Vancouver, Vancouver",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 28,
    "stage": "Group Stage",
    "group": "Group A",
    "team1": "Mexico",
    "team2": "Korea Republic",
    "team1_code": "mx",
    "team2_code": "kr",
    "utc_time": "2026-06-19T01:00:00Z",
    "venue": "Guadalajara Stadium, Guadalajara",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 29,
    "stage": "Group Stage",
    "group": "Group D",
    "team1": "USA",
    "team2": "Australia",
    "team1_code": "us",
    "team2_code": "au",
    "utc_time": "2026-06-19T19:00:00Z",
    "venue": "Seattle Stadium, Seattle",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 30,
    "stage": "Group Stage",
    "group": "Group C",
    "team1": "Scotland",
    "team2": "Morocco",
    "team1_code": "gb-sct",
    "team2_code": "ma",
    "utc_time": "2026-06-19T22:00:00Z",
    "venue": "Boston Stadium, Boston",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 31,
    "stage": "Group Stage",
    "group": "Group C",
    "team1": "Brazil",
    "team2": "Haiti",
    "team1_code": "br",
    "team2_code": "ht",
    "utc_time": "2026-06-20T00:30:00Z",
    "venue": "Philadelphia Stadium, Philadelphia",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 32,
    "stage": "Group Stage",
    "group": "Group D",
    "team1": "Türkiye",
    "team2": "Paraguay",
    "team1_code": "tr",
    "team2_code": "py",
    "utc_time": "2026-06-20T03:00:00Z",
    "venue": "San Francisco Bay Area Stadium, Santa Clara",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 33,
    "stage": "Group Stage",
    "group": "Group F",
    "team1": "Netherlands",
    "team2": "Sweden",
    "team1_code": "nl",
    "team2_code": "se",
    "utc_time": "2026-06-20T17:00:00Z",
    "venue": "Houston Stadium, Houston",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 34,
    "stage": "Group Stage",
    "group": "Group E",
    "team1": "Germany",
    "team2": "Côte d'Ivoire",
    "team1_code": "de",
    "team2_code": "ci",
    "utc_time": "2026-06-20T20:00:00Z",
    "venue": "Toronto Stadium, Toronto",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 35,
    "stage": "Group Stage",
    "group": "Group E",
    "team1": "Ecuador",
    "team2": "Curaçao",
    "team1_code": "ec",
    "team2_code": "cw",
    "utc_time": "2026-06-21T00:00:00Z",
    "venue": "Kansas City Stadium, Kansas City",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 36,
    "stage": "Group Stage",
    "group": "Group F",
    "team1": "Tunisia",
    "team2": "Japan",
    "team1_code": "tn",
    "team2_code": "jp",
    "utc_time": "2026-06-21T04:00:00Z",
    "venue": "Monterrey Stadium, Monterrey",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 37,
    "stage": "Group Stage",
    "group": "Group H",
    "team1": "Spain",
    "team2": "Saudi Arabia",
    "team1_code": "es",
    "team2_code": "sa",
    "utc_time": "2026-06-21T16:00:00Z",
    "venue": "Atlanta Stadium, Atlanta",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 38,
    "stage": "Group Stage",
    "group": "Group G",
    "team1": "Belgium",
    "team2": "IR Iran",
    "team1_code": "be",
    "team2_code": "ir",
    "utc_time": "2026-06-21T19:00:00Z",
    "venue": "Los Angeles Stadium, Los Angeles",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 39,
    "stage": "Group Stage",
    "group": "Group H",
    "team1": "Uruguay",
    "team2": "Cabo Verde",
    "team1_code": "uy",
    "team2_code": "cv",
    "utc_time": "2026-06-21T22:00:00Z",
    "venue": "Miami Stadium, Miami",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 40,
    "stage": "Group Stage",
    "group": "Group G",
    "team1": "New Zealand",
    "team2": "Egypt",
    "team1_code": "nz",
    "team2_code": "eg",
    "utc_time": "2026-06-22T01:00:00Z",
    "venue": "BC Place Vancouver, Vancouver",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 41,
    "stage": "Group Stage",
    "group": "Group J",
    "team1": "Argentina",
    "team2": "Austria",
    "team1_code": "ar",
    "team2_code": "at",
    "utc_time": "2026-06-22T17:00:00Z",
    "venue": "Dallas Stadium, Arlington",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 42,
    "stage": "Group Stage",
    "group": "Group I",
    "team1": "France",
    "team2": "Iraq",
    "team1_code": "fr",
    "team2_code": "iq",
    "utc_time": "2026-06-22T21:00:00Z",
    "venue": "Philadelphia Stadium, Philadelphia",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 43,
    "stage": "Group Stage",
    "group": "Group I",
    "team1": "Norway",
    "team2": "Senegal",
    "team1_code": "no",
    "team2_code": "sn",
    "utc_time": "2026-06-23T00:00:00Z",
    "venue": "New York/New Jersey Stadium, East Rutherford",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 44,
    "stage": "Group Stage",
    "group": "Group J",
    "team1": "Jordan",
    "team2": "Algeria",
    "team1_code": "jo",
    "team2_code": "dz",
    "utc_time": "2026-06-23T03:00:00Z",
    "venue": "San Francisco Bay Area Stadium, Santa Clara",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 45,
    "stage": "Group Stage",
    "group": "Group K",
    "team1": "Portugal",
    "team2": "Uzbekistan",
    "team1_code": "pt",
    "team2_code": "uz",
    "utc_time": "2026-06-23T17:00:00Z",
    "venue": "Houston Stadium, Houston",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 46,
    "stage": "Group Stage",
    "group": "Group L",
    "team1": "England",
    "team2": "Ghana",
    "team1_code": "gb-eng",
    "team2_code": "gh",
    "utc_time": "2026-06-23T20:00:00Z",
    "venue": "Boston Stadium, Boston",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 47,
    "stage": "Group Stage",
    "group": "Group L",
    "team1": "Panama",
    "team2": "Croatia",
    "team1_code": "pa",
    "team2_code": "hr",
    "utc_time": "2026-06-23T23:00:00Z",
    "venue": "Toronto Stadium, Toronto",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 48,
    "stage": "Group Stage",
    "group": "Group K",
    "team1": "Colombia",
    "team2": "Congo DR",
    "team1_code": "co",
    "team2_code": "cd",
    "utc_time": "2026-06-24T02:00:00Z",
    "venue": "Guadalajara Stadium, Guadalajara",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 49,
    "stage": "Group Stage",
    "group": "Group B",
    "team1": "Bosnia and Herzegovina",
    "team2": "Qatar",
    "team1_code": "ba",
    "team2_code": "qa",
    "utc_time": "2026-06-24T19:00:00Z",
    "venue": "Seattle Stadium, Seattle",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 50,
    "stage": "Group Stage",
    "group": "Group B",
    "team1": "Switzerland",
    "team2": "Canada",
    "team1_code": "ch",
    "team2_code": "ca",
    "utc_time": "2026-06-24T19:00:00Z",
    "venue": "BC Place Vancouver, Vancouver",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 51,
    "stage": "Group Stage",
    "group": "Group C",
    "team1": "Morocco",
    "team2": "Haiti",
    "team1_code": "ma",
    "team2_code": "ht",
    "utc_time": "2026-06-24T22:00:00Z",
    "venue": "Atlanta Stadium, Atlanta",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 52,
    "stage": "Group Stage",
    "group": "Group C",
    "team1": "Scotland",
    "team2": "Brazil",
    "team1_code": "gb-sct",
    "team2_code": "br",
    "utc_time": "2026-06-24T22:00:00Z",
    "venue": "Miami Stadium, Miami",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 53,
    "stage": "Group Stage",
    "group": "Group A",
    "team1": "South Africa",
    "team2": "Korea Republic",
    "team1_code": "za",
    "team2_code": "kr",
    "utc_time": "2026-06-25T01:00:00Z",
    "venue": "Monterrey Stadium, Monterrey",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 54,
    "stage": "Group Stage",
    "group": "Group A",
    "team1": "Czechia",
    "team2": "Mexico",
    "team1_code": "cz",
    "team2_code": "mx",
    "utc_time": "2026-06-25T01:00:00Z",
    "venue": "Mexico City Stadium, Mexico City",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 55,
    "stage": "Group Stage",
    "group": "Group E",
    "team1": "Curaçao",
    "team2": "Côte d'Ivoire",
    "team1_code": "cw",
    "team2_code": "ci",
    "utc_time": "2026-06-25T20:00:00Z",
    "venue": "Philadelphia Stadium, Philadelphia",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 56,
    "stage": "Group Stage",
    "group": "Group E",
    "team1": "Ecuador",
    "team2": "Germany",
    "team1_code": "ec",
    "team2_code": "de",
    "utc_time": "2026-06-25T20:00:00Z",
    "venue": "New York/New Jersey Stadium, East Rutherford",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 57,
    "stage": "Group Stage",
    "group": "Group F",
    "team1": "Japan",
    "team2": "Sweden",
    "team1_code": "jp",
    "team2_code": "se",
    "utc_time": "2026-06-25T23:00:00Z",
    "venue": "Dallas Stadium, Arlington",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 58,
    "stage": "Group Stage",
    "group": "Group F",
    "team1": "Tunisia",
    "team2": "Netherlands",
    "team1_code": "tn",
    "team2_code": "nl",
    "utc_time": "2026-06-25T23:00:00Z",
    "venue": "Kansas City Stadium, Kansas City",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 59,
    "stage": "Group Stage",
    "group": "Group D",
    "team1": "Paraguay",
    "team2": "Australia",
    "team1_code": "py",
    "team2_code": "au",
    "utc_time": "2026-06-26T02:00:00Z",
    "venue": "San Francisco Bay Area Stadium, Santa Clara",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 60,
    "stage": "Group Stage",
    "group": "Group D",
    "team1": "Türkiye",
    "team2": "USA",
    "team1_code": "tr",
    "team2_code": "us",
    "utc_time": "2026-06-26T02:00:00Z",
    "venue": "Los Angeles Stadium, Los Angeles",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 61,
    "stage": "Group Stage",
    "group": "Group I",
    "team1": "Norway",
    "team2": "France",
    "team1_code": "no",
    "team2_code": "fr",
    "utc_time": "2026-06-26T19:00:00Z",
    "venue": "Boston Stadium, Boston",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 62,
    "stage": "Group Stage",
    "group": "Group I",
    "team1": "Senegal",
    "team2": "Iraq",
    "team1_code": "sn",
    "team2_code": "iq",
    "utc_time": "2026-06-26T19:00:00Z",
    "venue": "Toronto Stadium, Toronto",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 63,
    "stage": "Group Stage",
    "group": "Group H",
    "team1": "Uruguay",
    "team2": "Spain",
    "team1_code": "uy",
    "team2_code": "es",
    "utc_time": "2026-06-27T00:00:00Z",
    "venue": "Guadalajara Stadium, Guadalajara",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 64,
    "stage": "Group Stage",
    "group": "Group H",
    "team1": "Cabo Verde",
    "team2": "Saudi Arabia",
    "team1_code": "cv",
    "team2_code": "sa",
    "utc_time": "2026-06-27T00:00:00Z",
    "venue": "Houston Stadium, Houston",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 65,
    "stage": "Group Stage",
    "group": "Group G",
    "team1": "Egypt",
    "team2": "IR Iran",
    "team1_code": "eg",
    "team2_code": "ir",
    "utc_time": "2026-06-27T03:00:00Z",
    "venue": "Seattle Stadium, Seattle",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 66,
    "stage": "Group Stage",
    "group": "Group G",
    "team1": "New Zealand",
    "team2": "Belgium",
    "team1_code": "nz",
    "team2_code": "be",
    "utc_time": "2026-06-27T03:00:00Z",
    "venue": "BC Place Vancouver, Vancouver",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 67,
    "stage": "Group Stage",
    "group": "Group L",
    "team1": "Panama",
    "team2": "England",
    "team1_code": "pa",
    "team2_code": "gb-eng",
    "utc_time": "2026-06-27T21:00:00Z",
    "venue": "New York/New Jersey Stadium, East Rutherford",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 68,
    "stage": "Group Stage",
    "group": "Group L",
    "team1": "Croatia",
    "team2": "Ghana",
    "team1_code": "hr",
    "team2_code": "gh",
    "utc_time": "2026-06-27T21:00:00Z",
    "venue": "Philadelphia Stadium, Philadelphia",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 69,
    "stage": "Group Stage",
    "group": "Group K",
    "team1": "Congo DR",
    "team2": "Uzbekistan",
    "team1_code": "cd",
    "team2_code": "uz",
    "utc_time": "2026-06-27T23:30:00Z",
    "venue": "Atlanta Stadium, Atlanta",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 70,
    "stage": "Group Stage",
    "group": "Group K",
    "team1": "Colombia",
    "team2": "Portugal",
    "team1_code": "co",
    "team2_code": "pt",
    "utc_time": "2026-06-27T23:30:00Z",
    "venue": "Miami Stadium, Miami",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 71,
    "stage": "Group Stage",
    "group": "Group J",
    "team1": "Jordan",
    "team2": "Argentina",
    "team1_code": "jo",
    "team2_code": "ar",
    "utc_time": "2026-06-28T02:00:00Z",
    "venue": "Dallas Stadium, Arlington",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 72,
    "stage": "Group Stage",
    "group": "Group J",
    "team1": "Algeria",
    "team2": "Austria",
    "team1_code": "dz",
    "team2_code": "at",
    "utc_time": "2026-06-28T02:00:00Z",
    "venue": "Kansas City Stadium, Kansas City",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 73,
    "stage": "Round of 32",
    "group": "Knockout",
    "team1": "Winner Group A",
    "team2": "Runner-up Group B",
    "team1_code": "tbd",
    "team2_code": "tbd",
    "utc_time": "2026-06-28T22:00:00Z",
    "venue": "Los Angeles Stadium, Los Angeles",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 74,
    "stage": "Round of 32",
    "group": "Knockout",
    "team1": "Runner-up Group A",
    "team2": "Runner-up Group C",
    "team1_code": "tbd",
    "team2_code": "tbd",
    "utc_time": "2026-06-29T02:00:00Z",
    "venue": "San Francisco Bay Area Stadium, Santa Clara",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 75,
    "stage": "Round of 32",
    "group": "Knockout",
    "team1": "Winner Group B",
    "team2": "Best 3rd A/C/D",
    "team1_code": "tbd",
    "team2_code": "tbd",
    "utc_time": "2026-06-29T22:00:00Z",
    "venue": "Boston Stadium, Boston",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 76,
    "stage": "Round of 32",
    "group": "Knockout",
    "team1": "Winner Group C",
    "team2": "Best 3rd B/E/F",
    "team1_code": "tbd",
    "team2_code": "tbd",
    "utc_time": "2026-06-30T02:00:00Z",
    "venue": "Seattle Stadium, Seattle",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 77,
    "stage": "Round of 32",
    "group": "Knockout",
    "team1": "Winner Group D",
    "team2": "Best 3rd C/G/H",
    "team1_code": "tbd",
    "team2_code": "tbd",
    "utc_time": "2026-06-30T22:00:00Z",
    "venue": "New York New Jersey Stadium, East Rutherford",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 78,
    "stage": "Round of 32",
    "group": "Knockout",
    "team1": "Runner-up Group D",
    "team2": "Runner-up Group E",
    "team1_code": "tbd",
    "team2_code": "tbd",
    "utc_time": "2026-07-01T02:00:00Z",
    "venue": "Dallas Stadium, Arlington",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 79,
    "stage": "Round of 32",
    "group": "Knockout",
    "team1": "Winner Group E",
    "team2": "Runner-up Group F",
    "team1_code": "tbd",
    "team2_code": "tbd",
    "utc_time": "2026-07-01T22:00:00Z",
    "venue": "Houston Stadium, Houston",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 80,
    "stage": "Round of 32",
    "group": "Knockout",
    "team1": "Winner Group F",
    "team2": "Best 3rd D/I/J",
    "team1_code": "tbd",
    "team2_code": "tbd",
    "utc_time": "2026-07-02T02:00:00Z",
    "venue": "Kansas City Stadium, Kansas City",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 81,
    "stage": "Round of 32",
    "group": "Knockout",
    "team1": "Winner Group G",
    "team2": "Runner-up Group H",
    "team1_code": "tbd",
    "team2_code": "tbd",
    "utc_time": "2026-07-02T22:00:00Z",
    "venue": "Philadelphia Stadium, Philadelphia",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 82,
    "stage": "Round of 32",
    "group": "Knockout",
    "team1": "Winner Group H",
    "team2": "Best 3rd E/K/L",
    "team1_code": "tbd",
    "team2_code": "tbd",
    "utc_time": "2026-07-03T02:00:00Z",
    "venue": "Miami Stadium, Miami",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 83,
    "stage": "Round of 32",
    "group": "Knockout",
    "team1": "Winner Group I",
    "team2": "Runner-up Group J",
    "team1_code": "tbd",
    "team2_code": "tbd",
    "utc_time": "2026-07-03T18:00:00Z",
    "venue": "Toronto Stadium, Toronto",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 84,
    "stage": "Round of 32",
    "group": "Knockout",
    "team1": "Winner Group J",
    "team2": "Best 3rd F/G/H",
    "team1_code": "tbd",
    "team2_code": "tbd",
    "utc_time": "2026-07-03T22:00:00Z",
    "venue": "Atlanta Stadium, Atlanta",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 85,
    "stage": "Round of 32",
    "group": "Knockout",
    "team1": "Winner Group K",
    "team2": "Runner-up Group L",
    "team1_code": "tbd",
    "team2_code": "tbd",
    "utc_time": "2026-07-04T02:00:00Z",
    "venue": "Vancouver Stadium, Vancouver",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 86,
    "stage": "Round of 32",
    "group": "Knockout",
    "team1": "Winner Group L",
    "team2": "Best 3rd I/K/L",
    "team1_code": "tbd",
    "team2_code": "tbd",
    "utc_time": "2026-07-04T18:00:00Z",
    "venue": "Monterrey Stadium, Monterrey",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 87,
    "stage": "Round of 32",
    "group": "Knockout",
    "team1": "Runner-up Group G",
    "team2": "Runner-up Group I",
    "team1_code": "tbd",
    "team2_code": "tbd",
    "utc_time": "2026-07-04T22:00:00Z",
    "venue": "Guadalajara Stadium, Guadalajara",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 88,
    "stage": "Round of 16",
    "group": "Knockout",
    "team1": "Winner Match 73",
    "team2": "Winner Match 74",
    "team1_code": "tbd",
    "team2_code": "tbd",
    "utc_time": "2026-07-04T22:00:00Z",
    "venue": "Philadelphia Stadium, Philadelphia",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 89,
    "stage": "Round of 32",
    "group": "Knockout",
    "team1": "Runner-up Group K",
    "team2": "Runner-up Group H",
    "team1_code": "tbd",
    "team2_code": "tbd",
    "utc_time": "2026-07-05T02:00:00Z",
    "venue": "Mexico City Stadium, Mexico City",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 90,
    "stage": "Round of 16",
    "group": "Knockout",
    "team1": "Winner Match 75",
    "team2": "Winner Match 76",
    "team1_code": "tbd",
    "team2_code": "tbd",
    "utc_time": "2026-07-05T02:00:00Z",
    "venue": "Houston Stadium, Houston",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 91,
    "stage": "Round of 16",
    "group": "Knockout",
    "team1": "Winner Match 77",
    "team2": "Winner Match 78",
    "team1_code": "tbd",
    "team2_code": "tbd",
    "utc_time": "2026-07-05T22:00:00Z",
    "venue": "New York New Jersey Stadium, East Rutherford",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 92,
    "stage": "Round of 16",
    "group": "Knockout",
    "team1": "Winner Match 79",
    "team2": "Winner Match 80",
    "team1_code": "tbd",
    "team2_code": "tbd",
    "utc_time": "2026-07-06T02:00:00Z",
    "venue": "Dallas Stadium, Arlington",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 93,
    "stage": "Round of 16",
    "group": "Knockout",
    "team1": "Winner Match 81",
    "team2": "Winner Match 82",
    "team1_code": "tbd",
    "team2_code": "tbd",
    "utc_time": "2026-07-06T22:00:00Z",
    "venue": "Atlanta Stadium, Atlanta",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 94,
    "stage": "Round of 16",
    "group": "Knockout",
    "team1": "Winner Match 83",
    "team2": "Winner Match 84",
    "team1_code": "tbd",
    "team2_code": "tbd",
    "utc_time": "2026-07-07T02:00:00Z",
    "venue": "Vancouver Stadium, Vancouver",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 95,
    "stage": "Round of 16",
    "group": "Knockout",
    "team1": "Winner Match 85",
    "team2": "Winner Match 86",
    "team1_code": "tbd",
    "team2_code": "tbd",
    "utc_time": "2026-07-07T22:00:00Z",
    "venue": "Seattle Stadium, Seattle",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 96,
    "stage": "Round of 16",
    "group": "Knockout",
    "team1": "Winner Match 87",
    "team2": "Winner Match 88",
    "team1_code": "tbd",
    "team2_code": "tbd",
    "utc_time": "2026-07-08T02:00:00Z",
    "venue": "Mexico City Stadium, Mexico City",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 97,
    "stage": "Quarter-final",
    "group": "Knockout",
    "team1": "Winner Match 89",
    "team2": "Winner Match 90",
    "team1_code": "tbd",
    "team2_code": "tbd",
    "utc_time": "2026-07-09T22:00:00Z",
    "venue": "Boston Stadium, Boston",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 98,
    "stage": "Quarter-final",
    "group": "Knockout",
    "team1": "Winner Match 91",
    "team2": "Winner Match 92",
    "team1_code": "tbd",
    "team2_code": "tbd",
    "utc_time": "2026-07-10T02:00:00Z",
    "venue": "Los Angeles Stadium, Los Angeles",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 99,
    "stage": "Quarter-final",
    "group": "Knockout",
    "team1": "Winner Match 93",
    "team2": "Winner Match 94",
    "team1_code": "tbd",
    "team2_code": "tbd",
    "utc_time": "2026-07-10T22:00:00Z",
    "venue": "Miami Stadium, Miami",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 100,
    "stage": "Quarter-final",
    "group": "Knockout",
    "team1": "Winner Match 95",
    "team2": "Winner Match 96",
    "team1_code": "tbd",
    "team2_code": "tbd",
    "utc_time": "2026-07-11T02:00:00Z",
    "venue": "Kansas City Stadium, Kansas City",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 101,
    "stage": "Semi-final",
    "group": "Knockout",
    "team1": "Winner Match 97",
    "team2": "Winner Match 98",
    "team1_code": "tbd",
    "team2_code": "tbd",
    "utc_time": "2026-07-15T01:00:00Z",
    "venue": "Dallas Stadium, Arlington",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": true
  },
  {
    "id": 102,
    "stage": "Semi-final",
    "group": "Knockout",
    "team1": "Winner Match 99",
    "team2": "Winner Match 100",
    "team1_code": "tbd",
    "team2_code": "tbd",
    "utc_time": "2026-07-16T01:00:00Z",
    "venue": "Atlanta Stadium, Atlanta",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": true
  },
  {
    "id": 103,
    "stage": "Third Place Match",
    "group": "Knockout",
    "team1": "Loser Match 101",
    "team2": "Loser Match 102",
    "team1_code": "tbd",
    "team2_code": "tbd",
    "utc_time": "2026-07-18T20:00:00Z",
    "venue": "Miami Stadium, Miami",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": false
  },
  {
    "id": 104,
    "stage": "Final",
    "group": "Knockout",
    "team1": "Winner Match 101",
    "team2": "Winner Match 102",
    "team1_code": "tbd",
    "team2_code": "tbd",
    "utc_time": "2026-07-19T20:00:00Z",
    "venue": "New York New Jersey Stadium, East Rutherford",
    "score1": null,
    "score2": null,
    "status": "Scheduled",
    "featured": true
  }
];

// Helper to generate flag HTML using FlagCDN with fallback
function getTeamFlagHTML(teamName, teamCode) {
  if (!teamCode || teamCode === "tbd") {
    return `<span class="flag-placeholder"><i class="fa-solid fa-circle-question"></i></span>`;
  }
  const code = teamCode.toLowerCase();
  return `<img src="https://flagcdn.com/w40/${code}.png" 
               srcset="https://flagcdn.com/w80/${code}.png 2x" 
               width="24" 
               height="18" 
               alt="${teamName} flag" 
               class="team-flag"
               onerror="this.style.display='none'; this.nextElementSibling.style.display='inline-block';">
          <span class="flag-placeholder" style="display:none;"><i class="fa-solid fa-futbol"></i></span>`;
}
